<div class="floating-input">
  <select id="{{ $name ?? 'country' }}" data-selected="{{ $selected ?? $value ?? '' }}" class="floating-input__field" name="{{ $name ?? 'country' }}"
    placeholder="@translate('Country')">
    <option value="" selected disabled hidden>@translate('Choose country here...')</option>

    <option value="Afganistan">@translate('Afghanistan')</option>
    <option value="Albania">@translate('Albania')</option>
    <option value="Algeria">@translate('Algeria')</option>
    <option value="American Samoa">@translate('American Samoa')</option>
    <option value="Andorra">@translate('Andorra')</option>
    <option value="Angola">@translate('Angola')</option>
    <option value="Anguilla">@translate('Anguilla')</option>
    <option value="Antigua & Barbuda">@translate('Antigua & Barbuda')</option>
    <option value="Argentina">@translate('Argentina')</option>
    <option value="Armenia">@translate('Armenia')</option>
    <option value="Aruba">@translate('Aruba')</option>
    <option value="Australia">@translate('Australia')</option>
    <option value="Austria">@translate('Austria')</option>
    <option value="Azerbaijan">@translate('Azerbaijan')</option>
    <option value="Bahamas">@translate('Bahamas')</option>
    <option value="Bahrain">@translate('Bahrain')</option>
    <option value="Bangladesh">@translate('Bangladesh')</option>
    <option value="Barbados">@translate('Barbados')</option>
    <option value="Belarus">@translate('Belarus')</option>
    <option value="Belgium">@translate('Belgium')</option>
    <option value="Belize">@translate('Belize')</option>
    <option value="Benin">@translate('Benin')</option>
    <option value="Bermuda">@translate('Bermuda')</option>
    <option value="Bhutan">@translate('Bhutan')</option>
    <option value="Bolivia">@translate('Bolivia')</option>
    <option value="Bonaire">@translate('Bonaire')</option>
    <option value="Bosnia & Herzegovina">@translate('Bosnia & Herzegovina')</option>
    <option value="Botswana">@translate('Botswana')</option>
    <option value="Brazil">@translate('Brazil')</option>
    <option value="British Indian Ocean Ter">@translate('British Indian Ocean Ter')</option>
    <option value="Brunei">@translate('Brunei')</option>
    <option value="Bulgaria">@translate('Bulgaria')</option>
    <option value="Burkina Faso">@translate('Burkina Faso')</option>
    <option value="Burundi">@translate('Burundi')</option>
    <option value="Cambodia">@translate('Cambodia')</option>
    <option value="Cameroon">@translate('Cameroon')</option>
    <option value="Canada">@translate('Canada')</option>
    <option value="Canary Islands">@translate('Canary Islands')</option>
    <option value="Cape Verde">@translate('Cape Verde')</option>
    <option value="Cayman Islands">@translate('Cayman Islands')</option>
    <option value="Central African Republic">@translate('Central African Republic')</option>
    <option value="Chad">@translate('Chad')</option>
    <option value="Channel Islands">@translate('Channel Islands')</option>
    <option value="Chile">@translate('Chile')</option>
    <option value="China">@translate('China')</option>
    <option value="Christmas Island">@translate('Christmas Island')</option>
    <option value="Cocos Island">@translate('Cocos Island')</option>
    <option value="Colombia">@translate('Colombia')</option>
    <option value="Comoros">@translate('Comoros')</option>
    <option value="Congo">@translate('Congo')</option>
    <option value="Cook Islands">@translate('Cook Islands')</option>
    <option value="Costa Rica">@translate('Costa Rica')</option>
    <option value="Cote DIvoire">@translate('Cote DIvoire')</option>
    <option value="Croatia">@translate('Croatia')</option>
    <option value="Cuba">@translate('Cuba')</option>
    <option value="Curaco">@translate('Curacao')</option>
    <option value="Cyprus">@translate('Cyprus')</option>
    <option value="Czech Republic">@translate('Czech Republic')</option>
    <option value="Denmark">@translate('Denmark')</option>
    <option value="Djibouti">@translate('Djibouti')</option>
    <option value="Dominica">@translate('Dominica')</option>
    <option value="Dominican Republic">@translate('Dominican Republic')</option>
    <option value="East Timor">@translate('East Timor')</option>
    <option value="Ecuador">@translate('Ecuador')</option>
    <option value="Egypt">@translate('Egypt')</option>
    <option value="El Salvador">@translate('El Salvador')</option>
    <option value="Equatorial Guinea">@translate('Equatorial Guinea')</option>
    <option value="Eritrea">@translate('Eritrea')</option>
    <option value="Estonia">@translate('Estonia')</option>
    <option value="Ethiopia">@translate('Ethiopia')</option>
    <option value="Falkland Islands">@translate('Falkland Islands')</option>
    <option value="Faroe Islands">@translate('Faroe Islands')</option>
    <option value="Fiji">@translate('Fiji')</option>
    <option value="Finland">@translate('Finland')</option>
    <option value="France">@translate('France')</option>
    <option value="French Guiana">@translate('French Guiana')</option>
    <option value="French Polynesia">@translate('French Polynesia')</option>
    <option value="French Southern Ter">@translate('French Southern Ter')</option>
    <option value="Gabon">@translate('Gabon')</option>
    <option value="Gambia">@translate('Gambia')</option>
    <option value="Georgia">@translate('Georgia')</option>
    <option value="Germany">@translate('Germany')</option>
    <option value="Ghana">@translate('Ghana')</option>
    <option value="Gibraltar">@translate('Gibraltar')</option>
    <option value="Great Britain">@translate('Great Britain')</option>
    <option value="Greece">@translate('Greece')</option>
    <option value="Greenland">@translate('Greenland')</option>
    <option value="Grenada">@translate('Grenada')</option>
    <option value="Guadeloupe">@translate('Guadeloupe')</option>
    <option value="Guam">@translate('Guam')</option>
    <option value="Guatemala">@translate('Guatemala')</option>
    <option value="Guinea">@translate('Guinea')</option>
    <option value="Guyana">@translate('Guyana')</option>
    <option value="Haiti">@translate('Haiti')</option>
    <option value="Hawaii">@translate('Hawaii')</option>
    <option value="Honduras">@translate('Honduras')</option>
    <option value="Hong Kong">@translate('Hong Kong')</option>
    <option value="Hungary">@translate('Hungary')</option>
    <option value="Iceland">@translate('Iceland')</option>
    <option value="Indonesia">@translate('Indonesia')</option>
    <option value="India">@translate('India')</option>
    <option value="Iran">@translate('Iran')</option>
    <option value="Iraq">@translate('Iraq')</option>
    <option value="Ireland">@translate('Ireland')</option>
    <option value="Isle of Man">@translate('Isle of Man')</option>
    <option value="Israel">@translate('Israel')</option>
    <option value="Italy">@translate('Italy')</option>
    <option value="Jamaica">@translate('Jamaica')</option>
    <option value="Japan">@translate('Japan')</option>
    <option value="Jordan">@translate('Jordan')</option>
    <option value="Kazakhstan">@translate('Kazakhstan')</option>
    <option value="Kenya">@translate('Kenya')</option>
    <option value="Kiribati">@translate('Kiribati')</option>
    <option value="Korea North">@translate('Korea North')</option>
    <option value="Korea Sout">@translate('Korea South')</option>
    <option value="Kuwait">@translate('Kuwait')</option>
    <option value="Kyrgyzstan">@translate('Kyrgyzstan')</option>
    <option value="Laos">@translate('Laos')</option>
    <option value="Latvia">@translate('Latvia')</option>
    <option value="Lebanon">@translate('Lebanon')</option>
    <option value="Lesotho">@translate('Lesotho')</option>
    <option value="Liberia">@translate('Liberia')</option>
    <option value="Libya">@translate('Libya')</option>
    <option value="Liechtenstein">@translate('Liechtenstein')</option>
    <option value="Lithuania">@translate('Lithuania')</option>
    <option value="Luxembourg">@translate('Luxembourg')</option>
    <option value="Macau">@translate('Macau')</option>
    <option value="Macedonia">@translate('Macedonia')</option>
    <option value="Madagascar">@translate('Madagascar')</option>
    <option value="Malaysia">@translate('Malaysia')</option>
    <option value="Malawi">@translate('Malawi')</option>
    <option value="Maldives">@translate('Maldives')</option>
    <option value="Mali">@translate('Mali')</option>
    <option value="Malta">@translate('Malta')</option>
    <option value="Marshall Islands">@translate('Marshall Islands')</option>
    <option value="Martinique">@translate('Martinique')</option>
    <option value="Mauritania">@translate('Mauritania')</option>
    <option value="Mauritius">@translate('Mauritius')</option>
    <option value="Mayotte">@translate('Mayotte')</option>
    <option value="Mexico">@translate('Mexico')</option>
    <option value="Midway Islands">@translate('Midway Islands')</option>
    <option value="Moldova">@translate('Moldova')</option>
    <option value="Monaco">@translate('Monaco')</option>
    <option value="Mongolia">@translate('Mongolia')</option>
    <option value="Montserrat">@translate('Montserrat')</option>
    <option value="Morocco">@translate('Morocco')</option>
    <option value="Mozambique">@translate('Mozambique')</option>
    <option value="Myanmar">@translate('Myanmar')</option>
    <option value="Nambia">@translate('Nambia')</option>
    <option value="Nauru">@translate('Nauru')</option>
    <option value="Nepal">@translate('Nepal')</option>
    <option value="Netherland Antilles">@translate('Netherland Antilles')</option>
    <option value="Netherlands">@translate('Netherlands (Holland, Europe)')</option>
    <option value="Nevis">@translate('Nevis')</option>
    <option value="New Caledonia">@translate('New Caledonia')</option>
    <option value="New Zealand">@translate('New Zealand')</option>
    <option value="Nicaragua">@translate('Nicaragua')</option>
    <option value="Niger">@translate('Niger')</option>
    <option value="Nigeria">@translate('Nigeria')</option>
    <option value="Niue">@translate('Niue')</option>
    <option value="Norfolk Island">@translate('Norfolk Island')</option>
    <option value="Norway">@translate('Norway')</option>
    <option value="Oman">@translate('Oman')</option>
    <option value="Pakistan">@translate('Pakistan')</option>
    <option value="Palau Island">@translate('Palau Island')</option>
    <option value="Palestine">@translate('Palestine')</option>
    <option value="Panama">@translate('Panama')</option>
    <option value="Papua New Guinea">@translate('Papua New Guinea')</option>
    <option value="Paraguay">@translate('Paraguay')</option>
    <option value="Peru">@translate('Peru')</option>
    <option value="Phillipines">@translate('Philippines')</option>
    <option value="Pitcairn Island">@translate('Pitcairn Island')</option>
    <option value="Poland">@translate('Poland')</option>
    <option value="Portugal">@translate('Portugal')</option>
    <option value="Puerto Rico">@translate('Puerto Rico')</option>
    <option value="Qatar">@translate('Qatar')</option>
    <option value="Republic of Montenegro">@translate('Republic of Montenegro')</option>
    <option value="Republic of Serbia">@translate('Republic of Serbia')</option>
    <option value="Reunion">@translate('Reunion')</option>
    <option value="Romania">@translate('Romania')</option>
    <option value="Russia">@translate('Russia')</option>
    <option value="Rwanda">@translate('Rwanda')</option>
    <option value="St Barthelemy">@translate('St Barthelemy')</option>
    <option value="St Eustatius">@translate('St Eustatius')</option>
    <option value="St Helena">@translate('St Helena')</option>
    <option value="St Kitts-Nevis">@translate('St Kitts-Nevis')</option>
    <option value="St Lucia">@translate('St Lucia')</option>
    <option value="St Maarten">@translate('St Maarten')</option>
    <option value="St Pierre & Miquelon">@translate('St Pierre & Miquelon')</option>
    <option value="St Vincent & Grenadines">@translate('St Vincent & Grenadines')</option>
    <option value="Saipan">@translate('Saipan')</option>
    <option value="Samoa">@translate('Samoa')</option>
    <option value="Samoa American">@translate('Samoa American')</option>
    <option value="San Marino">@translate('San Marino')</option>
    <option value="Sao Tome & Principe">@translate('Sao Tome & Principe')</option>
    <option value="Saudi Arabia">@translate('Saudi Arabia')</option>
    <option value="Senegal">@translate('Senegal')</option>
    <option value="Seychelles">@translate('Seychelles')</option>
    <option value="Sierra Leone">@translate('Sierra Leone')</option>
    <option value="Singapore">@translate('Singapore')</option>
    <option value="Slovakia">@translate('Slovakia')</option>
    <option value="Slovenia">@translate('Slovenia')</option>
    <option value="Solomon Islands">@translate('Solomon Islands')</option>
    <option value="Somalia">@translate('Somalia')</option>
    <option value="South Africa">@translate('South Africa')</option>
    <option value="Spain">@translate('Spain')</option>
    <option value="Sri Lanka">@translate('Sri Lanka')</option>
    <option value="Sudan">@translate('Sudan')</option>
    <option value="Suriname">@translate('Suriname')</option>
    <option value="Swaziland">@translate('Swaziland')</option>
    <option value="Sweden">@translate('Sweden')</option>
    <option value="Switzerland">@translate('Switzerland')</option>
    <option value="Syria">@translate('Syria')</option>
    <option value="Tahiti">@translate('Tahiti')</option>
    <option value="Taiwan">@translate('Taiwan')</option>
    <option value="Tajikistan">@translate('Tajikistan')</option>
    <option value="Tanzania">@translate('Tanzania')</option>
    <option value="Thailand">@translate('Thailand')</option>
    <option value="Togo">@translate('Togo')</option>
    <option value="Tokelau">@translate('Tokelau')</option>
    <option value="Tonga">@translate('Tonga')</option>
    <option value="Trinidad & Tobago">@translate('Trinidad & Tobago')</option>
    <option value="Tunisia">@translate('Tunisia')</option>
    <option value="Turkey">@translate('Turkey')</option>
    <option value="Turkmenistan">@translate('Turkmenistan')</option>
    <option value="Turks & Caicos Is">@translate('Turks & Caicos Is')</option>
    <option value="Tuvalu">@translate('Tuvalu')</option>
    <option value="Uganda">@translate('Uganda')</option>
    <option value="United Kingdom">@translate('United Kingdom')</option>
    <option value="Ukraine">@translate('Ukraine')</option>
    <option value="United Arab Erimates">@translate('United Arab Emirates')</option>
    <option value="United States of America">@translate('United States of America')</option>
    <option value="Uraguay">@translate('Uruguay')</option>
    <option value="Uzbekistan">@translate('Uzbekistan')</option>
    <option value="Vanuatu">@translate('Vanuatu')</option>
    <option value="Vatican City State">@translate('Vatican City State')</option>
    <option value="Venezuela">@translate('Venezuela')</option>
    <option value="Vietnam">@translate('Vietnam')</option>
    <option value="Virgin Islands (Brit)">@translate('Virgin Islands (Brit)')</option>
    <option value="Virgin Islands (USA)">@translate('Virgin Islands (USA)')</option>
    <option value="Wake Island">@translate('Wake Island')</option>
    <option value="Wallis & Futana Is">@translate('Wallis & Futana Is')</option>
    <option value="Yemen">@translate('Yemen')</option>
    <option value="Zaire">@translate('Zaire')</option>
    <option value="Zambia">@translate('Zambia')</option>
    <option value="Zimbabwe">@translate('Zimbabwe')</option>
  </select>
  <label for="{{ $name ?? 'country' }}">@translate('Country')</label>
</div>